name: table_order
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  carousel_slider: ^5.0.0
  responsive_builder: ^0.7.1
  scoped_model: ^2.0.0
  fluttertoast: ^8.2.0
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  firebase_database: ^11.1.4
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.4
  font_awesome_flutter: ^10.7.0
  google_sign_in: ^6.2.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  permission_handler: ^11.3.1
  geoflutterfire_plus: ^0.0.32

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
