const Map<String, Map<String, List<String>>> cityDistrictMap = {
  'Đà Nẵng': {
    'Sơn Trà': ['Phường An Hải Bắc', 'Phường An Hải Đông', 'Phường Mân Thái'],
    'Ngũ Hành Sơn': ['Phường Khuê Mỹ', 'Phường Mỹ An', 'Phường Hòa Hải'],
    'Hải Châu': ['Phường Phước Ninh', 'Phường Hòa Cường Bắc', 'Phường Nam Dương'],
    'Liên Chiểu': ['Phường Hòa Hiệp Bắc', 'Phường Hòa Khánh Bắc'],
    'Thanh Khê': ['Phường Thanh Khê Đông', 'Phường Chính Gián'],
    'Cẩm Lệ': ['Phường Hòa Thọ Đông', 'Phường Khuê Trung'],
    'Hòa Vang': ['Phường Phú Mỹ', 'Phường Hòa Phú'],
  },
  'Hà Nội': {
    'Ba Đình': ['Phường Đội Cấn', 'Phường Kim Mã'],
    'Hoàn Kiếm': ['Phường Hàng Bài', 'Phường Cửa Nam'],
    'Đống Đa': ['Phường Quảng An', 'Phường Thịnh Quang'],
    'Cầu Giấy': ['Phường Dịch Vọng', 'Phường Mai Dịch'],
  },
  'TP HCM': {
    'Quận 1': ['Phường Bến Nghé', 'Phường Tân Định'],
    'Quận 3': ['Phường Võ Thị Sáu', 'Phường 11'],
    'Quận 7': ['Phường Tân Hưng', 'Phường Phú Mỹ'],
    'Tân Bình': ['Phường 1', 'Phường 4'],
  },
};

// List of days in Vietnamese
final List<String> daysOfTheWeek = [
  'Sunday',
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
];

// List of available keywords
final List<String> availableKeywords = [
  'Hải sản',
  'Đồ nướng',
  'Kiểu Hàn Quốc',
  'Kiểu Nhật',
  'Kiểu Ý',
  'Kiểu Trung Quốc',
  'Kiểu Mỹ',
  'Kiểu Âu',
  'Kiểu Thái',
  'Kiểu Mexico',
  'Kiểu Ấn Độ',
  'Kiểu Pháp',
  'Kiểu Singapore',
  'Kiểu Tây Ban Nha',
  'Kiểu Malaysia',
  'Kiểu Brazil',
  'Kiểu Nga',
  'Kiểu Argentina',
  'Kiểu Đông Âu',
  'Kiểu Trung Á',
  'Kiểu Hy Lạp',
  'Kiểu Indonesia',
  'Kiểu Ba Lan',
  'Kiểu Cuba',
  'Kiểu Sri Lanka',
  'Kiểu Jamaica',
  'Kiểu Pakistan',
  'Pizza',
  'Sushi',
  'Bít tết',
  'Bánh ngọt',
  'Burgers',
  'Pasta',
  'Cà phê',
  'Salad',
  'Đồ ăn nhanh',
  'Fast food',
  'Món kết hợp',
  'Thức ăn đường phố',
  'Quán bar',
  'Quán rượu',
  'Quán rượu vang',
  'Quán bán trái cây giải khát',
  'Món ăn chữa bệnh',
  'Đương đại',
  'Buffet',
  'Cajun & Creole',
  'Quảng Đông',
  'Phong cách Fusion Nhật Bản',
  'Quán bar phục vụ đồ ăn',
  'Món Ấn',
  'Món Hoa',
  'Món Việt',
  'Bữa sáng',
  'Bữa trưa',
  'Bữa tối',
  'Bữa nửa buổi',
  'Bánh ngọt Nhật Bản',
  'Miền Nam nước Ý',
  'Catalonia',
  'Naples',
  'Campania',
  'Thực phẩm đặc sản',
  'Ẩm thực Bắc Kinh',
  'Tân Cương',
  'Quán phục vụ đồ ngọt Nhật Bản',
  'Kiểu Ba Tư',
  'Kiểu Armenia',
  'Kiểu Uzbek',
  'Kiểu Azerbaijan',
  'Algeria',
  'Bánh mì',
  'Bánh bao',
  'Quảng Đông'
];

